name: ğŸš€ Build & Push Docker Image

on:
  push:
    branches:
      - main   # dispara o build quando houver push na branch main

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout do cÃ³digo
      - name: ğŸ“¥ Checkout do repositÃ³rio
        uses: actions/checkout@v3

      # Login no Docker Hub
      - name: ğŸ”‘ Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build & Push
      - name: ğŸ› ï¸ Build & Push imagem
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: alfabiz2025/flyer-service:latest
